# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_SECRET }}

          # Options
          user: JiveOff
          template: classic
          base: header
          config_timezone: Europe/Paris
          plugin_introduction: no
          plugin_introduction_title: yes
          plugin_isocalendar: no
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: recent
          plugin_music_played_at: yes
          plugin_music_playlist: https://open.spotify.com/embed/playlist/3BfTj2wFRi6I8NYEN5LNL2
          plugin_music_provider: spotify
          plugin_music_user: .user.login
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
